apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: econsent-api
spec:
  params:
    - name: GIT_REPO
      type: string
    - name: GIT_REVISION
      type: string
    - name: IMAGE_REGISTRY_URL
      type: string
    - name: APP_NAME
      type: string
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
    - name: build-and-push-image
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: $(params.IMAGE_REGISTRY_URL)/$(params.APP_NAME):$(params.GIT_REVISION)
